#!/bin/bash

op="+";
num=1;
tail -n 0 -f v_op |
while true;
do
	read line;

	if [[ "$line" != "QUIT" && $(echo "$line" | grep -E -o "^([0-9]+)|\*|\+$" | wc -l) == 0 ]];
	then
		echo "Program falure";
		exit 1;
	fi;

	case "$line" in
		"QUIT")
			echo "Quit the program";
			exit 0;
		;;
		"+")
			op="+";
			echo "Operation +";
		;;
		"*")
			op="*";
			echo "Operation *";
		;;
		*)
			let num=$num$op$line;
			echo $num;
		;;
	esac;
done;
