#!/bin/bash

for pid in $(ps -e -o pid | tail -n +2);  do
	if [[ -f "/proc/$pid/statm" ]]; then
		awk '{printf("%d:%dKb\n", '"$pid"', ($2-$3)/4096)}' < "/proc/$pid/statm";
	fi;
done | sort -r -n -t ":" -k2 > "iv.log";
